### ISSUE TITLE
[Bug]  Descriptive error messages

### ISSUE THREAD

**Issue by F-Camuso** [EduardoGiacomini/mafcust-frontend#24]
### I am submiting a: 
* [ ] Feature request; 
* [X] Bug fixes.

### Current behaviour

Before the change in the errors from the backend, all the problems were reported in the front. Now, only the backend errors are showing to the user 

### Expected behaviour

We should have descriptive errors when something wrong happens.

### How to reproduce the bug?
It happens when:
1. The user type a wrong password
2. Wrong username
3. And other minors alerts affected by the errors change in the backend

**Comment by EduardoGiacomini** [comment]
I fixed this problem in the [backend #30](https://github.com/EduardoGiacomini/mafcust-backend/pull/30).
